/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Algoritmos.BellmanFord;
import Algoritmos.MapaCiudades;
import Grafos.Arista;
import Grafos.Grafo;
import Grafos.Vertice;
import java.awt.BorderLayout;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author 52644
 */
public class Presentacion extends javax.swing.JFrame {

    private static MapaPanel mp;

    public Presentacion() {
        initComponents();
        mostrarMapa();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMapa = new javax.swing.JPanel();
        btnKruskal = new javax.swing.JButton();
        BtnBellmanFord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelMapaLayout = new javax.swing.GroupLayout(panelMapa);
        panelMapa.setLayout(panelMapaLayout);
        panelMapaLayout.setHorizontalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1128, Short.MAX_VALUE)
        );
        panelMapaLayout.setVerticalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        btnKruskal.setText("Kruskal");
        btnKruskal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKruskalActionPerformed(evt);
            }
        });

        BtnBellmanFord.setText("Bellman ford");
        BtnBellmanFord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBellmanFordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKruskal, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(BtnBellmanFord, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKruskal, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(BtnBellmanFord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKruskalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKruskalActionPerformed
        Grafo g = Algoritmos.AlgoritmosMST.aplicarKruskal(mp.getGrafo());
        mp.actualizarGrafo(g);
    }//GEN-LAST:event_btnKruskalActionPerformed
    private double obtenerPesoArista(Grafo grafo, Vertice origen, Vertice destino) {

        for (Arista arista : grafo.getVecinos(origen)) {
            if (arista.getDestino().equals(destino)) {
                return arista.getPeso();
            }
        }

        for (Arista arista : grafo.getVecinos(destino)) {
            if (arista.getDestino().equals(origen)) {
                return arista.getPeso();
            }
        }
        return 0.0;
    }
    private void BtnBellmanFordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBellmanFordActionPerformed

        String origenNombre = JOptionPane.showInputDialog(this, "Ingrese la ciudad de origen:");
        if (origenNombre == null || origenNombre.trim().isEmpty()) {
            return;
        }

        String destinoNombre = JOptionPane.showInputDialog(this, "Ingrese la ciudad de destino:");
        if (destinoNombre == null || destinoNombre.trim().isEmpty()) {
            return;
        }

        Grafo grafoOriginal = mp.getGrafo();
        Vertice origen = null;
        Vertice destino = null;

        for (Vertice v : grafoOriginal.getVertices()) {
            if (v.getNombre().equalsIgnoreCase(origenNombre.trim())) {
                origen = v;
            }
            if (v.getNombre().equalsIgnoreCase(destinoNombre.trim())) {
                destino = v;
            }
        }

        if (origen == null || destino == null) {
            JOptionPane.showMessageDialog(this, "Una o ambas ciudades no se encontraron en el grafo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (origen.equals(destino)) {
            JOptionPane.showMessageDialog(this, "La ciudad de origen y destino no pueden ser la misma.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Map<String, Object> resultado = BellmanFord.BellmanFord(grafoOriginal, origen, destino);

        if ((Boolean) resultado.get("ciclo negativo")) {
            JOptionPane.showMessageDialog(this, "Se detecto un ciclo de peso negativo. No se puede calcular la ruta más corta.", "Ciclo Negativo Detectado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        List<Vertice> ruta = (List<Vertice>) resultado.get("ruta");
        if (ruta == null || ruta.size() < 2) {
            JOptionPane.showMessageDialog(this, "No se encontro una ruta entre las ciudades seleccionadas.", "Sin Ruta", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Grafo grafoRuta = new Grafo();
        ruta.forEach(grafoRuta::agregarVertice);

        for (int i = 0; i < ruta.size() - 1; i++) {
            Vertice u = ruta.get(i);
            Vertice v = ruta.get(i + 1);
            double peso = obtenerPesoArista(grafoOriginal, u, v);
            grafoRuta.agregarArista(u, v, peso);
        }

        
        mp.actualizarGrafo(grafoRuta);


    }//GEN-LAST:event_BtnBellmanFordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion().setVisible(true);
            }
        });
    }

    private void mostrarMapa() {
        Grafo grafoCiudades = MapaCiudades.construirGrafo();

        MapaPanel mapaPanel = new MapaPanel(grafoCiudades);
        this.mp = mapaPanel;
        panelMapa.setLayout(new BorderLayout());
        panelMapa.add(mapaPanel, BorderLayout.CENTER);

        mapaPanel.setSize(panelMapa.getSize());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBellmanFord;
    private javax.swing.JButton btnKruskal;
    private javax.swing.JPanel panelMapa;
    // End of variables declaration//GEN-END:variables
}
